apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-todoapp-postgres-0
  namespace: todoapp
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: todoapp-postgres-pv
  resources:
    requests:
      storage: 16Gi
