when:
  - branch: [main]
    event: [push]

variables:
  - &go_image "golang:1.25-bookworm"
  - &node_image "node:22-bookworm-slim"
  - &kubectl_image "alpine/k8s:1.31.0"
  - &trivy_image "aquasec/trivy:0.69.3"
  - &buildx_image "woodpeckerci/plugin-docker-buildx:4"
  - &cosign_image "ghcr.io/sigstore/cosign/cosign:v2.4.0"
  - &gitleaks_image "zricethezav/gitleaks:latest"
  - &hadolint_image "hadolint/hadolint:latest-debian"
  - &kubescore_image "zegl/kube-score:latest"
  - &conftest_image "openpolicyagent/conftest:latest"
  - &k6_image "grafana/k6:latest"
  - &oasdiff_image "tufin/oasdiff:latest"
  - &email_image "drillster/drone-email"
steps:

  - name: build-core
    image: *buildx_image
    privileged: true

    settings:
      repo: akawatmor/todoapp-core
      dockerfile: src/phase2-final/backend/Dockerfile
      context: src/phase2-final/backend

      tags:
        - "${CI_COMMIT_SHA:0:7}"
        - latest

      cache_from:
        - type=registry,ref=akawatmor/todoapp-core:buildcache

      cache_to:
        - type=registry,ref=akawatmor/todoapp-core:buildcache,mode=max

      username:
        from_secret: DOCKER_USERNAME

      password:
        from_secret: DOCKER_PASSWORD

  - name: build-web
    image: *buildx_image
    privileged: true

    settings:
      repo: akawatmor/todoapp-web
      dockerfile: src/phase2-final/frontend/Dockerfile
      context: src/phase2-final/frontend

      tags:
        - "${CI_COMMIT_SHA:0:7}"
        - latest

      cache_from:
        - type=registry,ref=akawatmor/todoapp-web:buildcache

      cache_to:
        - type=registry,ref=akawatmor/todoapp-web:buildcache,mode=max

      username:
        from_secret: DOCKER_USERNAME

      password:
        from_secret: DOCKER_PASSWORD

  - name: build-gate
    image: alpine:3.20

    depends_on:
      - build-core
      - build-web

    commands:
      - echo "Build completed"